name: AO workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cod
      uses: actions/checkout@v2

    - name: Print Hello Ahcene, world!
      run: |
        echo "Hello, Ahcene!"
